/*	Name: Sammi Sax
	netID: srs190010
	Date: 8/29/19
	
	Homework 2, softball game ticket income*/
#include <iostream>
#include <iomanip>
using namespace std;

int main()
{


	//declare variables with no initialization 
	double numTicketA, numTicketB, numTicketC;

		//prompt user to input values for each ticket type sold
		cout << "Enter the number of ticket type A sold" << endl;
		cin >> numTicketA;
		cout << endl;

		cout << "Enter the number of ticket type B sold" << endl;
		cin >> numTicketB;
		cout << endl;

		cout << "Enter the number of ticket type C sold" << endl;
		cin >> numTicketC;
		cout << endl;


	//calculate the income generated per ticket type
	double incTicketA = (numTicketA * 13.00);
	double incTicketB = (numTicketB * 11.00);
	double incTicketC = (numTicketC * 7.00);


	//set precision to 2 decimal places
	cout.precision(2);

		//output income per ticket type to the console
		cout << "The income generated by ticket type A is $" << fixed << incTicketA << endl;
		cout << endl;
		cout << "The income generated by ticket type B is $" << fixed << incTicketB  << endl;
		cout << endl;
		cout << "The income generated by ticket type C is $" << fixed << incTicketC << endl;
		cout << endl;

	
	//calculate the total revenue from all ticket sales
	double totalTicketRev = (incTicketA + incTicketB + incTicketC);

		//display the total revenue on the console
		cout << "The total ticket revenue generated over all is $" << totalTicketRev << fixed << endl << endl;

	//calculate the average income per ticket sold and output the value to the console
		double avrgTicketInc = (totalTicketRev / (numTicketA + numTicketB + numTicketC));
		cout << "The average income generated per ticket is $" << fixed << avrgTicketInc << endl;

	return 0;
}
